### ISSUE TITLE
How to handle non supported characters?

### ISSUE THREAD

**Issue by srhise** [zenorocha/voice-elements#16]
It seems in the demo, when I insert certain characters (such as a number with a decimal like "59.1") The demo breaks and nothing on the page will function until I completely close and re-open chrome. Is there anything error handling or checking for not supported characters? Is this something to take up with the polymer component, if so where does that live?

This is amazing, I think it will be huge for web accessibility.

**Comment by zenorocha** [comment]
Hey @srhise,

This project uses the Web Speech API which means that I don't have control over voice synthesis validation, only browser vendors do. I recommend filling out an issue on Chromium bug tracker.
