### ISSUE TITLE
How to get Project when input is also project

### ISSUE THREAD

**Issue by ApertureStudiosMedia** [zenorocha/voice-elements#20]
I am having one word being pronounced as a similar word. I would like to know how to make the input word "project" to be defined as a works in the making or as in a media "project".

**Comment by zenorocha** [comment]
Hey @ApertureStudiosMedia,

This project uses the Web Speech API which means that I don't have control over pronunciation, only browser vendors do.

Thanks for reporting and sorry for my delay on answering this issue.
