### ISSUE TITLE
<voice-elements> not working on Topeka-based app

### ISSUE THREAD

**Issue by MrRod** [zenorocha/voice-elements#21]
Hi everyone,

I'm having some trouble implementing <voice-elements> in my Polymer app. It's based on Polymer's quiz demo app and I'm trying to use the voice recognition element to submit answers. This is my code:

    <link rel="import" href="../quiz-base.html">
    <link rel="import" href="../../paper-input/paper-input.html">
    <link rel="import" href="../../voice-elements/voice-player.html">
    <link rel="import" href="../../voice-elements/voice-recognition.html">

    <polymer-element name="quiz-voice-recognition" extends="quiz-base">
    <template>

    <style>  
    :host {
    padding: 40px;
    }
    
    :host-context(.wide) {
    width: 304px;
    margin: 0 auto;
    }
  
    paper-input {
    width: 100%;
    height: 48px;
    }
	
    core-icon[icon="av:mic"] {
    width: 120px;
    height: 120px;
    }  
     </style>
  
    <div>{{quiz.start}}</div>

    <voice-recognition id="recognition-element"></voice-recognition>

    <script>
    var form = document.querySelector('#recognition-form'),
    input = document.querySelector('#recognition-input'),
    element = document.querySelector('#recognition-element');
    form.addEventListener('submit', function(e) {
    e.preventDefault();
    element.start();
    });
    element.addEventListener('result', function(e) {
    input.textContent = e.detail.result;
    });
    </script>

    <form id="recognition-form">
    <fieldset>
    <textarea id="recognition-input" readonly=""></textarea>
    </fieldset>
    <fieldset>
    <button id="recognition-submit">Start!</button>
    </fieldset>
    </form>

    <div>{{quiz.end}}</div>
    </template>

    <script>
    Polymer('quiz-voice-recognition', {
    
    eventDelegates: {
    'input': 'answered'
    },
    
    isCorrect: function() {
    return this.areEqual(this.value, this.quiz.answer);
    },
    
    areEqual: function(s1, s2) {
    return s1 && s2 && s1.trim().toLowerCase() === s2.trim().toLowerCase();
    }
    
    });
    </script>
    </polymer-element>

Everytime I load the page I get the following error and when clicking the submit button it doesn't trigger the authorization popup to enable voice recognition as seen in the demo site: **Uncaught TypeError: Cannot read property 'addEventListener' of null**

**Comment by zenorocha** [comment]
Hey @MrRod, please isolate your problem properly instead of copy & pasting your entire code.

http://stackoverflow.com/help/mcve

The error says that your `element` variable is null.
