### ISSUE TITLE
Pronunciation training and assessment

### ISSUE THREAD

**Issue by altaihero** [zenorocha/voice-elements#22]
Hello
I am making text Pronunciation web application for language learning.
if i use "voice-elements" can i check user Pronunciation. When user read some text, sentence or word
application give score for user Pronunciation. 

How about Pronunciation training and assessment in "voice-elements" ?

**Comment by zenorocha** [comment]
Hey @altaihero,

This project uses the Web Speech API which means that I don't have control over training and assessment, only browser vendors do.

Thanks for the suggestion and sorry for my delay on answering this issue.
