### ISSUE TITLE
voice-player crashes when text length > 306

### ISSUE THREAD

**Issue by cch5ng** [zenorocha/voice-elements#29]
hi, I think this is awesome that you have implemented voice-elements. I got to hear the presentation at JS.LA a while back. I am testing the voice-player out for a class project and it is crashing when I try to play a string > about 306 or 308 characters.
after the crash, even if I refresh my browser, the voicePlayer.speak() function does not recover. if I restart my webserver, the speak() function will recover. I don't know where to search for error messages. thanks.
(Chrome 44.0 on Mac OSX 10.10.4)

**Comment by zenorocha** [comment]
Hey @cch5ng, thanks for reporting!

This project uses the Web Speech API which means that I don't have control over synthesis length, only browser vendors do. I recommend filling out an issue on Chromium bug tracker.
