### ISSUE TITLE
Polymer 2.0 support

### ISSUE THREAD

**Issue by atifwaqar** [zenorocha/voice-elements#41]
This is an awesome element, Just curios to know if you guys are going to upgrade it in Polymer 2.0?

**Comment by zenorocha** [comment]
Hey @atifwaqar, I don't plan to upgrade it. But if you're willing to do that, please send a pull request.

**Comment by atifwaqar** [comment]
@zenorocha, I dont have a usecase for this component yet, but as soon as I have a usecase, i will upgrade your code and send you a pull request. :)
