### ISSUE TITLE
Add <a-voice> </a-voice> element - For voice control

### ISSUE THREAD

**Issue by HansUXdev** [zenorocha/voice-elements#7]
This idea is intended to optimize web browsing on AR-like devices such as Google Glass. However it could just as easily be used on phones.

End Goal:
```
               <a-voice ph="fuh-net-ik" href="...">phonetic name</a-voice>
```
ph = phonetic attribute -> could be used to optimize voice based search engines later

Anyhow thanks @zenorocha  for suggesting I post this as an "issue" lol

**Comment by zenorocha** [comment]
Hey @HansUXdev,

This project uses the Web Speech API which means that I don't have control over phonetic pronunciation.

Thanks for suggesting and sorry for my delay on answering this issue.

**Comment by corysimmons** [comment]
Aww. No Google TTS natural voices? :[
