### ISSUE TITLE
voice-player crash the all app in firefox and all unsupported browsers

### ISSUE THREAD

**Issue by jmorille** [zenorocha/voice-elements#9]
In firefox, the code below throw a **TypeError :  this.speech is undefined**
```javascript
textChanged: function() {
                this.speech.text = this.text;
},
```

Some controls should be welcome in order to don't crash all app when this.speech is not initialize in created function.
like
```javascript
textChanged: function() {
    if ( this.speech) {
                this.speech.text = this.text;
   }
},
```

**Comment by zenorocha** [comment]
This should fix this problem: https://github.com/zenorocha/voice-elements/blob/master/src/voice-player.html#L29-L31

Thanks for reporting @jmorille!

**Comment by zenorocha** [comment]
And sorry for the delay :/
